# Site settings
title: Dickson Tam
email: dicksont650(at)gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Independent web developer @ San Francisco.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dicksont.github.io" # the base hostname & protocol for your site
twitter_username: dicksontam
github_username:  dicksont

# Build settings
markdown: kramdown
